import { join } from "node:path";
import { parseFrontmatter } from "../lib/frontmatter.js";
import { renderCodexMcp } from "../lib/toml.js";
import type { Assets, SyncContext, Target } from "../lib/types.js";

/**
 * Codex reads `AGENTS.md` (project root, or `~/.codex/AGENTS.md` globally), custom prompts
 * from `~/.codex/prompts/*.md`, and MCP servers from `~/.codex/config.toml`. Prompts and
 * MCP config are user-level only; in project mode just the root AGENTS.md is emitted.
 */
export const codex: Target = {
  name: "codex",
  write(assets: Assets, ctx: SyncContext) {
    const { writer } = ctx;
    const rules = parseFrontmatter(ctx.mode === "global" ? assets.globalRules : assets.projectRules).body;

    if (rules.trim()) {
      const agentsPath = ctx.mode === "global"
        ? join(ctx.home, ".codex", "AGENTS.md")
        : join(ctx.projectDir, "AGENTS.md");
      writer.write(agentsPath, ensureNewline(rules));
    }

    if (ctx.mode === "global") {
      // Custom prompts — plain markdown, Claude-only frontmatter dropped.
      for (const cmd of assets.commands) {
        writer.write(join(ctx.home, ".codex", "prompts", `${cmd.name}.md`), ensureNewline(cmd.body));
      }
      if (Object.keys(assets.mcpServers).length > 0) {
        // Emit a standalone snippet rather than rewriting the user's whole config.toml.
        writer.write(
          join(ctx.home, ".codex", "clanker-forge.mcp.toml"),
          headerComment() + renderCodexMcp(assets.mcpServers),
        );
      }
    } else {
      if (assets.commands.length > 0) {
        writer.skip(join(ctx.projectDir, ".codex"), "Codex prompts are user-level; run with --global");
      }
    }

    if (assets.subagents.length > 0) {
      writer.skip(join(ctx.home, ".codex", "agents"), "Codex has no subagent equivalent; skipped");
    }
  },
};

function headerComment(): string {
  return "# Generated by clanker-forge. Paste these tables into ~/.codex/config.toml.\n\n";
}

function ensureNewline(text: string): string {
  return text.endsWith("\n") ? text : `${text}\n`;
}
