import { join } from "node:path";
import { parseFrontmatter } from "../lib/frontmatter.js";
import { resolveModel } from "../lib/models.js";
import { renderCodexAgent, renderCodexMcp } from "../lib/toml.js";
import type { Assets, SyncContext, Target } from "../lib/types.js";

/**
 * Codex reads `AGENTS.md` (project root, or `~/.codex/AGENTS.md` globally), custom prompts
 * from `~/.codex/prompts/*.md`, MCP servers from `~/.codex/config.toml`, and custom agents
 * from `.codex/agents/*.toml`. Prompts and MCP config are user-level only; agents and the
 * root AGENTS.md are emitted in both modes.
 */
export const codex: Target = {
  name: "codex",
  write(assets: Assets, ctx: SyncContext) {
    const { writer } = ctx;
    const rules = parseFrontmatter(ctx.mode === "global" ? assets.globalRules : assets.projectRules).body;

    if (rules.trim()) {
      const agentsPath = ctx.mode === "global"
        ? join(ctx.home, ".codex", "AGENTS.md")
        : join(ctx.projectDir, "AGENTS.md");
      writer.write(agentsPath, ensureNewline(rules));
    }

    if (ctx.mode === "global") {
      // Custom prompts — plain markdown, Claude-only frontmatter dropped.
      for (const cmd of assets.commands) {
        writer.write(join(ctx.home, ".codex", "prompts", `${cmd.name}.md`), ensureNewline(cmd.body));
      }
      if (Object.keys(assets.mcpServers).length > 0) {
        // Emit a standalone snippet rather than rewriting the user's whole config.toml.
        writer.write(
          join(ctx.home, ".codex", "clanker-forge.mcp.toml"),
          headerComment() + renderCodexMcp(assets.mcpServers),
        );
      }
    } else {
      if (assets.commands.length > 0) {
        writer.skip(join(ctx.projectDir, ".codex"), "Codex prompts are user-level; run with --global");
      }
    }

    // Custom agents → .codex/agents/*.toml (user-level globally, project-scoped otherwise).
    const agentsDir = ctx.mode === "global"
      ? join(ctx.home, ".codex", "agents")
      : join(ctx.projectDir, ".codex", "agents");
    for (const agent of assets.subagents) {
      const fm = agent.frontmatter;
      writer.write(
        join(agentsDir, `${agent.name}.toml`),
        renderCodexAgent({
          name: fm.name ?? agent.name,
          description: fm.description ?? "",
          developerInstructions: agent.body,
          model: resolveModel("codex", fm.model),
          readonly: /\b(Write|Edit)\b/.test(fm.disallowedTools ?? ""),
        }),
      );
    }
  },
};

function headerComment(): string {
  return "# Generated by clanker-forge. Paste these tables into ~/.codex/config.toml.\n\n";
}

function ensureNewline(text: string): string {
  return text.endsWith("\n") ? text : `${text}\n`;
}
